collections:
  verschijningsplaatsen:
    output: true

defaults:
  - scope:
      path: ""
      type: "verschijningsplaatsen"
    values:
      layout: "verschijningsplaats"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"